### ISSUE TITLE
Configuration File (wincmd.ini) issues

### ISSUE THREAD

**Issue by wolfferine** [rddim/TotalCommanderPortable#2]
1st things 1st: Thanks for creating this PortableApss package for Total Commander.

Upon testing this version i found out that the launch parameter(s) somehow are not being "picked up" by Total Commander
So Total Commander will keep on using the configuration file (wincmd.ini) from:

%HOMEDRIVE%%HOMEPATH%\AppData\Roaming\GHISLER

Instead of using the configuration file (wincmd.ini) at location:
PortableApps\TotalCommanderPortable\Data\settings

**Comment by Jaro122** [comment]
Hi thanks for your work will you also create a portable version of 10.52 ?

**Comment by rddim** [comment]
@wolfferine 
Could you test with the latest update?

@Jaro122 
Done, sorry for the delay, I was busy last month
https://github.com/rddim/TotalCommanderPortable/releases/latest

**Comment by Jaro122** [comment]
Thanks for your time 👍
________________________________
Od: Rusi Dimitrov ***@***.***>
Odoslané: streda 23. novembra 2022 22:29
Komu: rddim/TotalCommanderPortable ***@***.***>
Kópia: Jaro122 ***@***.***>; Mention ***@***.***>
Predmet: Re: [rddim/TotalCommanderPortable] Configuration File (wincmd.ini) issues (#2)


@wolfferine<https://github.com/wolfferine>
Could you test with the latest update?

@Jaro122<https://github.com/Jaro122>
Done, sorry for the delay, I was busy last month
https://github.com/rddim/TotalCommanderPortable/releases/latest
